/*
 * EL USUARIO ENVIA CARACTERES POR COMUNICACION SERIAL, EL MASTER LO RECIBE Y EL MASTER 
 * LO ENVIA AL ESCLAVO Y EL ESCLAVO RECIBE ESTOS DATOS 
 */
 #include<Wire.h>
 char dato;// VARAIBAL QUE SE UTILIZA PARA ALMACENAR CADA DATO TIPO CHAR
void setup() {
  Wire.begin();//COMIENZA LA COMUNICACION 12C
  Serial.begin(9600);//PUERTO SERIAL

}

void loop() {
if(Serial.available()>0){ //VERIFICA SI ESTA DISPONIBLE EL PUERTO DE COMUNICACIÓN
  dato=Serial.read();//LEE LOS DATOS Y LOS ALMACENA
  Wire.beginTransmission(6);//TRANSMITE OS DATOS HACIA EL INDICADOR 6 PARA QUE ESTE LO RECIBA SIEMPRE Y CUANDO HAYA UN ESCLAVO 6
  Wire.write(dato);
  Wire.endTransmission();
}
}
